### ISSUE TITLE
On Microsoft Edge 20, no Subject Images are loaded during the 'transcribe' phase.

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/shakespeares_world#142]
Expected Behaviour:
* After clicking "Get Started" or navigating to http://preview.zooniverse.org/folgerdemo/#/transcribe, the app should load one subject image, which is to then be classified by user input.

Actual Behaviour:
* Upon clicking "Get Started" or Navigating to http://preview.zooniverse.org/folgerdemo/#/transcribe, the app does NOT load a subject image. Instead, users only see the background image of an eight-pointed star.

Test Details: 
* Win 10/Edge 20/Not logged into Zooniverse - ERROR CONFIRMED

**Comment by simoneduca** [comment]
@shaunanoordin thanks for the heads up. What do you get in the console?

**Comment by shaunanoordin** [comment]
There are two consistent errors in the Edge dev console that I get whenever I click "Get Started" or navigating directly to the transcribe section.

-- First --
TypeError: Object doesn't support property or method 'getElementsByClassName'
   at ga (https://code.jquery.com/jquery-2.1.4.min.js:2:6684)
   at find (https://code.jquery.com/jquery-2.1.4.min.js:2:23408)
   at a (http://preview.zooniverse.org/folgerdemo/js/main.js:2:30748)
   at e (http://preview.zooniverse.org/folgerdemo/js/main.js:2:29952)
   at L (http://preview.zooniverse.org/folgerdemo/js/main.js:14:18454)
   at M (http://preview.zooniverse.org/folgerdemo/js/main.js:14:13082)
   at M (http://preview.zooniverse.org/folgerdemo/js/main.js:14:13170)
   at T (http://preview.zooniverse.org/folgerdemo/js/main.js:14:11975)
   at Anonymous function (http://preview.zooniverse.org/folgerdemo/js/main.js:12:10485)
   at rt (http://preview.zooniverse.org/folgerdemo/js/main.js:14:22861) <svg xmlns="http://www.w3.org/2000/svg" class="svg" width="100%" height="100%" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" marking-surface="" />

-- Second --

TypeError: Object doesn't support property or method 'resizeAndCentre'
   at o (http://preview.zooniverse.org/folgerdemo/js/main.js:4:7045)
   at h.prototype.$digest (http://preview.zooniverse.org/folgerdemo/js/main.js:15:22446)
   at Anonymous function (http://preview.zooniverse.org/folgerdemo/js/main.js:15:23827)
   at o (http://preview.zooniverse.org/folgerdemo/js/main.js:14:6618)
   at Anonymous function (http://preview.zooniverse.org/folgerdemo/js/main.js:14:8049)

**Comment by shaunanoordin** [comment]
Update: The _"Object doesn't support property or method 'getElementsByClassName'"_ error has been traced to MarkingSurfaceFactory.init()'s use of element.find(".rotate-container")

Diagnosis:
* IE and Edge do not play well with SVG.
* In Chrome, FF, etc, an SVG element and a HTML element are similar and have element.getElementsByClassName().
* However, in IE, the SVG element does not have that function, which is called by Jquery's $.find().

Suggested Solution/Workaround:
* For IE/Edge, use querySelectorAll() instead of $.find() for SVGs.
* First instance of error detected at MarkingSurfaceFactory.init(), but a change may be required in multiple areas of the code.

**Comment by simoneduca** [comment]
Thanks @shaunanoordin! Yes, the problem is that Internet Explorer supports JS `getElementsByClassName` method (which is used by Jquery `.find()` method) in the DOM, but not on SVG Elements.

Here https://github.com/jquery/sizzle/issues/322 there's a possible solution. Failing that, I think swapping `.find()` with `querySelectorAll`, as suggested in the OW issue, should help.
